name: Deploy to Prod

on:
  push:
    branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to prod
        uses: TwanLuttik/gh-action-scp@1.0.1
        with:
          host: ${{secrets.SERVER_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: ${{secrets.SERVER_USERNAME}}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          local: ./dist/*
          remote: /etc/projects/reasonstoswallow/
          
          
