name: Deploy to Prod

on:
  push:
    branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # - name: Checkout main branch
      #   uses: actions/checkout@v2

      # - name: Setup node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      # - name: Build application
      #   run: npm run build

      # - name: Copy Build Files
      #   run: ls -a -R $GITHUB_WORKSPACE
  
      - name: Deploy to prod
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
            SERVER_HOST: ${{secrets.SERVER_HOST}}
            SSH_PORT: ${{secrets.SSH_PORT}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -r -i private_key.pem -P $SSH_PORT $GITHUB_WORKSPACE/home/runner/work/reasonstoswallow-fe/reasonstoswallow-fe/build/* $SERVER_USERNAME@$SERVER_HOST:/etc/projects/reasonstoswallow/
          rm private_key.pem  
