name: Deploy to Prod

on:
  push:
    branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Copy Build Files
        run: ls -a -R $GITHUB_WORKSPACE
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config << END
          Host prod
            HostName $SERVER_HOST
            User $SERVER_USERNAME
            Port $SSH_PORT
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
          SERVER_HOST: ${{secrets.SERVER_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
      - name: Deploy to prod
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
            SERVER_HOST: ${{secrets.SERVER_HOST}}
            SSH_PORT: ${{secrets.SSH_PORT}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp prod $GITHUB_WORKSPACE/home/runner/work/reasonstoswallow-fe/reasonstoswallow-fe/build/* $SERVER_USERNAME@$SERVER_HOST:/etc/projects/reasonsto
          rm private_key.pem  
