name: Deploy to Prod

on:
  push:
    branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Copy Build Files
        run: ls -a -R $GITHUB_WORKSPACE

      - name: Deploy to prod
        uses: mschmitt/rsync-with-ssh-agent@49f36eb07a49df1ef6e504491276f078513e9ab8
        with:
          SSH_HOST: ${{secrets.SERVER_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_USER: ${{secrets.SERVER_USERNAME}}
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          RSYNC_LOCAL_PATH: $GITHUB_WORKSPACE/home/runner/work/reasonstoswallow-fe/reasonstoswallow-fe/build/
          RSYNC_REMOTE_PATH: /etc/projects/reasonstoswallow/
          
          
