name: Deploy to Prod

on:
  push:
    branches:
       - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Copy Build Files
        run: ls -a -R $GITHUB_WORKSPACE

      - name: Deploy to prod
        run: |
          scp -r $GITHUB_WORKSPACE/home/runner/work/reasonstoswallow-fe/reasonstoswallow-fe/build/* $SERVER_USERNAME@$SERVER_HOST:$SSH_PORT/etc/projects/reasonstoswallow/
          env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      
          
          
